### ISSUE TITLE
Use consistent naming for `styles` files

### ISSUE THREAD

**Issue by gromxyz** [thorchain/asgardex-electron#1677]
## Description
We had a lot of contributors in this codebase, so sometimes the naming of the files can be inconsistent.
If someone wants to help out, this could be a good first issue.

## TODO
- [ ] Find a list of the files containing: `*.style.ts`, `*.style.tsx`, `*.styles.tsx`
- [ ] Rename them to: `*.styles.ts`
- [ ] Verify that app renders correctly
