### ISSUE TITLE
[Epic] Support DOGE

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2001]
- [x] Enable pool **DONE** #2003
- [x] Mimir: `PAUSELPDOGE`|`HALTDOGETRADING`|`HALTDOGECHAIN` (example endpoint: https://stagenet-thornode.ninerealms.com/thorchain/mimir) **DONE** #2007
- [x] Introduce `Client` of [xchain-doge](https://github.com/xchainjs/xchainjs-lib/tree/master/packages/xchain-doge) - depends on https://github.com/xchainjs/xchainjs-lib/issues/396 **DONE** #2022
- [x] Show `address` in `wallet` -> `settings` **DONE**  #2023 
- [x] Show balances to `wallet` -> `assets` overview **DONE**  #2024 
- [x] `AssetDetail` component  **DONE**  #2024 
- [x] `Send` component **DONE** #2026
- [x] `Swap` **DONE** #2026
- [x] `sym` deposit #2026
- [x] `sym` withdraw #2026

Hint: Take PRs for introducing LTC mentioned in #899 as references how to introduce a new chain in ASGARDEX.
