### ISSUE TITLE
[Epic] Support Terra

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2002]
- [x] ~Mimir: PAUSELPTERRA|HALTTERRATRADING|HALTTERRACHAIN (mimir endpoint: https://stagenet-thornode.ninerealms.com/thorchain/mimir)~ **DONE**  #2197
- [x] ~Enable pool~ **DONE** #2193
- [x] ~Introduce `Client` of `xchain-terra` - currently in WIP (Discord https://discord.com/channels/838986635756044328/842252939149967382/927940056726011934)~ **DONE** #2190
- [x] ~Show `address` in `wallet` -> `settings`~ **DONE** #2195
- [x] ~Show balances to `wallet` -> `assets` overview~ **DONE** #2195
- [x] ~`AssetDetail` component~ #2201
- [x] ~`Send` component~ #2201  #2208 #2209
- [x] ~`Swap`~ **DONE** #2214
- [x] ~`sym` deposit~ **DONE** #2214
- [x] ~`sym` withdraw~ **DONE** (test needed only)

Hint: Take PRs for introducing LTC mentioned in #899 as references how to introduce a new chain in ASGARDEX.
