### ISSUE TITLE
Prepare v0.6.1

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2006]
## Description

Prepare next release {version}

## TODOs

- [x] Create branch `release/{version-number}` from latest `develop`
- [x] Disable DOGE actions (swap/deposit): `useMimirHalt` -> `haltDogeChain: true`
- [x] Bump version number in `package.json`
- [x] Update CHANGELOG.md
- [x] Create DRAFT release page at GH linked to `release/{version-number}` branch
- [x] ADD release notes to DRAFT release page
- [ ] Sign binaries as described [here](https://github.com/thorchain/Resources/blob/master/admin-GPG-keys.md) and add signed message to DRAFT release page
- [ ] Check binaries by running on `macOS`, `Windows` and `Linux`
- [ ] Publish release
