### ISSUE TITLE
 Pre-build v0.8.0 throws exception on Windows 

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2086]
## Error on Windows 10

No issue on macOS or Linux btw.
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Could not locale the bindings file. Tried:

...
```

~~DRAFT release page to download the binary (*.exe) https://github.com/thorchain/asgardex-electron/releases/tag/untagged-701d56d89f5d63112905~~

## TODOs

- [x] ~~Try`windows-2020` - #2087~~ _**FAILED...**_
- [x] ~~Remove `force-rebuild-native-deps` script~~ #2088 _**FAILED...**_
- [x] ~~Try latest [`Electron@17.0.1`](https://www.electronjs.org/releases/stable#17.0.1)~~ #2089 _**FAILED...**_
- [x] ~~Try [`electron-rebuild`](https://github.com/electron/electron-rebuild)~~ - #2090 _**already part of `electron-builder`**_
- [x] Stick with `windows2019` (`vs2022` does not support version of `node-gyp`, which is provided by `npm@8.x` - see https://github.com/actions/virtual-environments/issues/4856#issuecomment-1043256330) #2091 '**FIXED IT** :+1:
