### ISSUE TITLE
[Ledger] Support Terra

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2198]
## TODOs

- [x] ~Show / verify address~ **DONE** #2216
- [x] ~Show balances~ **DONE** #2217
- [x] ~Send "standard", `swap` + `deposit` txs~ **DONE** #2218
