### ISSUE TITLE
 [Ledger] Support ETH/ERC20

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2255]
## TODOs

- [x] ~Show / verify address~ **DONE** #2256 
- [x] ~Show balances~ **DONE** #2257
- [x] ~Check "approve" status~ **DONE** #2260
- [x] ~Send "approve" txs~ **DONE** #2260
- [x] ~Send "standard" txs~ **DONE** #2264 
- [x] ~Send `upgrade` txs~ **DONE** #2266
- [x] ~Send `swap` txs~ **DONE** #2265  
- [x] ~Send `deposit` txs~ **DONE** #2266
