### ISSUE TITLE
[Epic] Support Cosmos (ATOM)

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2288]
- [x] ~Support Mimir flags: `PAUSELPGAIA|HALTGAIATRADING|HALTGAIACHAIN` (check https://stagenet-thornode.ninerealms.com/thorchain/mimir)~ **DONE** #2289
- [x] ~Enable pool~ **DONE** #2290
- [x] ~Introduce `Client` of `xchain-cosmos`~ **DONE** #2291
- [x] ~Show `address` in `wallet` -> `settings`~ **DONE**  #2292 
- [x] ~Show balances to `wallet` -> `assets` overview~ **DONE**  #2292 
- [x] ~`AssetDetail` component~ **DONE** #2295
- [x] ~`Send` component~ **DONE** #2296
- [x] ~`Swap`~ DONE #2297
- [x] ~`sym` deposit~ DONE #2297
- [x] ~`sym` withdraw~ DONE #2297
