### ISSUE TITLE
[Ledger] Support Cosmos/ATOM

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2301]
## TODOs

- [ ] Show / verify address
- [ ] Show balances
- [ ] Send "standard" txs
- [ ] Send `swap` txs
- [ ] Send `deposit` txs

**Comment by veado** [comment]
Shipped in [v1.17.0](https://github.com/thorchain/asgardex-electron/releases/tag/v1.17.0)
