### ISSUE TITLE
[Epic] Ledger support Avalanche (AVAX)

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2422]
- [ ] Show / verify address
- [ ] Show balances
- [ ] Send "standard" txs
- [ ] Send `swap` / `deposit` txs

(similar to #2301, but for AVAX)
