### ISSUE TITLE
[Epic] Savers

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#2431]
- [ ] ADD screen
- [ ] Business logic to ADD
- [ ] Withdraw screen
- [ ] Withdraw logic to ADD
- [ ] Savers STATS screen
- [ ] Business logic to get STATS data

Memos:
- Memo to add: `+:btc/btc`
- Memo to withdraw:` -:btc/btc:10000` 

Endpoints:
- THORNode
   - https://thornode.ninerealms.com/thorchain/pools 
   - https://thornode.ninerealms.com/thorchain/pool/btc.btc/savers 
   - https://thornode.ninerealms.com/thorchain/pool/btc.btc/saver/bc1qcxssye4j6730h7ehgega3gyykkuwgdgmmpu62n
- Midgard: 
    - TBD

Discord #wallet-lounge :eyes: Thread https://discord.com/channels/838986635756044328/957805538119417916/1036762987123445811
