### ISSUE TITLE
Final Checklist Before Publishing For Fork

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#4]
## Mandatory
- [x] Purged all ERB stuff
- [x] Set up all dependencies for ASGARDEX 
- [x] Audited all repo files and directory setup
- [x] Imported THORChain Styles, Fonts #11
- [x] Validated unit, component, e2e testing process
- [x] Validated local build process
- [x] `test.yml` Github action on every push to Master
- [x] `build.yml` Github action on every tagged commit to Master
- [ ] ~`release.yml` Github action on every tagged commit to Master~
- [x] GPG Verified all contributors, added keys to `thorchain-admin`
- [x] Rehearsed Package Signing with key contributors

## Desired
- [x] Mac notarisation (local)
- [x] Mac notarisation in Github Actions
